# Generated by Django 3.1.7 on 2021-05-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('andr_update', '0002_auto_20210507_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAndruserRecordTableau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('andruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='andr_update.andruser')),
            ],
        ),
        migrations.CreateModel(
            name='BotAndruserRecordTableauEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_for_andruser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tableau_entries', to='andr_update.andruser')),
                ('tableau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tableau_entries', to='andr_record.botandruserrecordtableau')),
            ],
        ),
    ]
