# Generated by Django 3.1.7 on 2021-05-16 19:11

import andr_omeda.andr_record.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('andr_update', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField(choices=[(9, 'not yet approved'), (1, 'terms'), (8, 'show welcome message.'), (2, 'get my last filled steuererklaerung table.'), (3, 'choose between en or de.'), (4, 'add new row'), (5, 'delete row'), (6, 'submit the table'), (7, 'exit')])),
            ],
        ),
        migrations.CreateModel(
            name='STERRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_draft', models.BooleanField(default=True, verbose_name='is_draft')),
                ('table_layout', models.JSONField(default=andr_omeda.andr_record.models._table_layout)),
                ('table_data', models.JSONField(default=andr_omeda.andr_record.models._table_data)),
                ('is_submitted', models.BooleanField(default=False, verbose_name='is_submitted')),
                ('andruser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='andr_update.andruser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlowQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=andr_omeda.andr_record.models._def_queue, size=None)),
                ('last_update_uuid', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=andr_omeda.andr_record.models._def_update_queue, size=None)),
                ('chat', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_queue', to='andr_update.chat')),
            ],
        ),
    ]
