# Generated by Django 3.1.7 on 2021-05-10 23:35

import andr_omeda.andr_record.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0002_auto_20210507_1921'),
        ('andr_record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STERRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_draft', models.BooleanField(default=True, verbose_name='is_draft')),
                ('table_layout', models.JSONField(default=andr_omeda.andr_record.models._table_layout)),
                ('table_data', models.JSONField(default=andr_omeda.andr_record.models._table_layout)),
                ('is_submitted', models.BooleanField(default=False, verbose_name='is_submitted')),
                ('andruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='andr_update.andruser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='botandruserrecordtableauentry',
            name='entry_for_andruser',
        ),
        migrations.RemoveField(
            model_name='botandruserrecordtableauentry',
            name='tableau',
        ),
        migrations.RemoveField(
            model_name='record',
            name='andruser',
        ),
        migrations.DeleteModel(
            name='BotAndruserRecordTableau',
        ),
        migrations.DeleteModel(
            name='BotAndruserRecordTableauEntry',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
