# Generated by Django 3.1.7 on 2021-05-11 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0002_auto_20210507_1921'),
        ('andr_record', '0002_auto_20210511_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sterrecord',
            name='andruser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='andr_update.andruser'),
        ),
    ]
