# Generated by Django 3.1.7 on 2021-05-11 02:46

import andr_omeda.andr_record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_record', '0003_auto_20210511_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sterrecord',
            name='table_data',
            field=models.JSONField(default=andr_omeda.andr_record.models._table_data),
        ),
    ]
