# Generated by Django 3.1.7 on 2021-05-11 08:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0002_auto_20210507_1921'),
        ('andr_record', '0004_auto_20210511_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField(choices=[(1, 'terms'), (2, 'get my last filled steuererklaerung table.'), (3, 'choose between en or de.'), (4, 'add new row'), (5, 'delete row'), (6, 'submit the table'), (7, 'exit')])),
            ],
        ),
        migrations.CreateModel(
            name='FlowQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow_queue', to='andr_update.chat')),
            ],
        ),
    ]
