# Generated by Django 3.1.7 on 2021-05-11 09:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_record', '0005_flownode_flowqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flownode',
            name='event',
            field=models.IntegerField(choices=[(1, 'terms'), (8, 'show welcome message.'), (2, 'get my last filled steuererklaerung table.'), (3, 'choose between en or de.'), (4, 'add new row'), (5, 'delete row'), (6, 'submit the table'), (7, 'exit')]),
        ),
        migrations.AlterField(
            model_name='flowqueue',
            name='queue',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[8], size=None),
        ),
    ]
