# Generated by Django 3.1.7 on 2021-05-11 16:29

import andr_omeda.andr_record.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_record', '0007_auto_20210511_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowqueue',
            name='last_update_uuid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=andr_omeda.andr_record.models._def_update_queue, size=None),
        ),
    ]
