# Generated by Django 3.1.7 on 2021-05-16 19:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('andr_update', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotERPOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_erp_name', models.CharField(max_length=255, unique=True, verbose_name='owner-erp-name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True, verbose_name='bot-token')),
                ('allowed_update_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None)),
                ('is_webhook_set', models.BooleanField(default=False, verbose_name='is_webhook_set')),
                ('webhook_result_description', models.CharField(blank=True, default='', max_length=300, verbose_name='webhook_error_description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chats', models.ManyToManyField(blank=True, related_name='bots', to='andr_update.Chat')),
                ('erp_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='andr_bot.boterpowner')),
            ],
        ),
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('error_during_creating', models.CharField(blank=True, default='', max_length=255, verbose_name='error')),
                ('bot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook', to='andr_bot.bot')),
            ],
            options={
                'unique_together': {('bot',)},
            },
        ),
    ]
