# Generated by Django 3.1.7 on 2021-03-06 22:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('name', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('is_webhook_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('created', models.DateTimeField(editable=False)),
                ('token', models.CharField(default='1616191667:AAFTcCNQSnt1ZDnDDCdbwVPSUxNSNtLT5uE', max_length=46, primary_key=True, serialize=False, verbose_name='token')),
            ],
            options={
                'unique_together': {('name', 'token')},
            },
        ),
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url')),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 3, 6, 22, 16, 14, 287796, tzinfo=utc), editable=False)),
                ('error_during_creating', models.CharField(blank=True, default='', max_length=255, verbose_name='error')),
                ('bot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook', to='andr_bot.bot')),
            ],
            options={
                'unique_together': {('bot',)},
            },
        ),
    ]
