# Generated by Django 3.1.7 on 2021-03-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.TextField(default='1616191667:AAFTcCNQSnt1ZDnDDCdbwVPSUxNSNtLT5uE', max_length=46, primary_key=True, serialize=False, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
