# Generated by Django 3.1.7 on 2021-04-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.TextField(default='1763314382:AAE0ZVW_QL4K0-u3NPrPXR-TtpyaP3IV4fw', max_length=46, primary_key=True, serialize=False, verbose_name='token'),
        ),
    ]
