# Generated by Django 3.1.7 on 2021-05-04 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_bot', '0002_auto_20210402_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotERPOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_erp_name', models.CharField(max_length=255, unique=True, verbose_name='owner-erp-name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='bot-token'),
        ),
        migrations.AlterUniqueTogether(
            name='bot',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bot',
            name='is_webhook_active',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='name',
        ),
        migrations.AddField(
            model_name='bot',
            name='erp_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='andr_bot.boterpowner'),
        ),
    ]
