# Generated by Django 3.1.7 on 2021-05-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_record', '0001_initial'),
        ('andr_bot', '0002_auto_20210507_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='tableau',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bot', to='andr_record.botandruserrecordtableauentry'),
        ),
    ]
