# Generated by Django 3.1.7 on 2021-05-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_bot', '0001_initial'),
        ('andr_moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatedobject',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='andr_bot.bot'),
        ),
    ]
