# Generated by Django 3.1.7 on 2021-05-15 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_bot', '0005_bot_chats'),
        ('andr_moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatedobjectlog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='andr_bot.boterpowner'),
        ),
    ]
