# Generated by Django 3.1.7 on 2021-05-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='for_erp_user',
            field=models.CharField(default='', max_length=255, verbose_name='for_erp_user'),
        ),
        migrations.AddField(
            model_name='update',
            name='related_to_bot',
            field=models.CharField(default='', max_length=50, verbose_name='related_to_bot'),
        ),
    ]
