# Generated by Django 3.1.7 on 2021-03-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='linked_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='linked_chat_id'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='slow_mode_delay',
            field=models.IntegerField(blank=True, null=True, verbose_name='slow_mode_delay'),
        ),
    ]
