# Generated by Django 3.1.7 on 2021-03-15 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='text')),
                ('voter_count', models.IntegerField(verbose_name='voter_count')),
                ('poll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='andr_update.poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollAnswerOptionsId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_value', models.IntegerField(null=True, verbose_name='')),
                ('poll_answers', models.ManyToManyField(related_name='option_ids', to='andr_update.PollAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMemberUpdated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(verbose_name='date')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='andr_update.chat')),
                ('update_for_chat_member', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_member', to='andr_update.update')),
                ('update_for_my_chat_member', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_chat_member', to='andr_update.update')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='andr_update.andruser')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='status')),
                ('custom_title', models.CharField(blank=True, max_length=255, verbose_name='status')),
                ('is_anonymous', models.BooleanField(blank=True, verbose_name='is_anonymous')),
                ('can_be_edited', models.BooleanField(blank=True, verbose_name='can_be_edited')),
                ('can_manage_chat', models.BooleanField(blank=True, verbose_name='can_manage_chat')),
                ('can_post_messages', models.BooleanField(blank=True, verbose_name='can_post_messages')),
                ('can_edit_messages', models.BooleanField(blank=True, verbose_name='can_edit_messages')),
                ('can_delete_messages', models.BooleanField(blank=True, verbose_name='can_delete_messages')),
                ('can_manage_voice_chats', models.BooleanField(blank=True, verbose_name='can_manage_voice_chats')),
                ('can_restrict_members', models.BooleanField(blank=True, verbose_name='can_restrict_members')),
                ('can_promote_members', models.BooleanField(blank=True, verbose_name='can_promote_members')),
                ('can_change_info', models.BooleanField(blank=True, verbose_name='can_change_info')),
                ('can_invite_users', models.BooleanField(blank=True, verbose_name='can_invite_users')),
                ('can_pin_messages', models.BooleanField(blank=True, verbose_name='can_pin_messages')),
                ('is_member', models.BooleanField(blank=True, verbose_name='is_member')),
                ('can_send_messages', models.BooleanField(blank=True, verbose_name='can_send_messages')),
                ('can_send_media_messages', models.BooleanField(blank=True, verbose_name='can_send_media_messages')),
                ('can_send_polls', models.BooleanField(blank=True, verbose_name='can_send_polls')),
                ('can_send_other_messages', models.BooleanField(blank=True, verbose_name='can_send_other_messages')),
                ('can_add_web_page_previews', models.BooleanField(blank=True, verbose_name='can_add_web_page_previews')),
                ('until_date', models.IntegerField(blank=True, verbose_name='until_date')),
                ('new_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_chat_member', to='andr_update.chatmemberupdated')),
                ('old_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='old_chat_member', to='andr_update.chatmemberupdated')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='andr_update.andruser')),
            ],
        ),
        migrations.CreateModel(
            name='ChatInviteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_link', models.TextField(verbose_name='invite_link')),
                ('is_primary', models.BooleanField(verbose_name='is_primary')),
                ('is_revoked', models.BooleanField(verbose_name='is_revoked')),
                ('expire_date', models.IntegerField(blank=True, verbose_name='expire_date')),
                ('member_limit', models.IntegerField(blank=True, max_length=99999, verbose_name='member_limit')),
                ('creator', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='andr_update.andruser')),
            ],
        ),
    ]
