# Generated by Django 3.1.7 on 2021-03-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andrid',
            name='week_order',
            field=models.IntegerField(null=True, verbose_name='week_order'),
        ),
    ]
