# Generated by Django 3.1.7 on 2021-03-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0002_auto_20210311_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andrid',
            name='week_order',
            field=models.IntegerField(default=0, verbose_name='week_order'),
        ),
    ]
