# Generated by Django 3.1.7 on 2021-05-11 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0003_andruser_is_terms_of_use_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
