# Generated by Django 3.1.7 on 2021-03-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0005_auto_20210323_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='andr_id',
            new_name='update_id',
        ),
    ]
