# Generated by Django 3.1.7 on 2021-04-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0007_auto_20210324_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='andr_update.andruser'),
        ),
    ]
