# Generated by Django 3.1.7 on 2021-04-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0008_auto_20210402_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinvitelink',
            name='chat_member_update',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='invite_link', to='andr_update.chatmemberupdated'),
        ),
        migrations.AlterField(
            model_name='chatinvitelink',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='andr_update.andruser'),
        ),
    ]
