# Generated by Django 3.1.7 on 2021-04-02 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0009_auto_20210402_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andruser',
            name='entity_mention',
        ),
        migrations.AddField(
            model_name='messageentity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='andr_update.andruser'),
        ),
    ]
