# Generated by Django 3.1.7 on 2021-04-02 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0010_auto_20210402_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageentity',
            name='message_captioned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caption_entities', to='andr_update.message'),
        ),
        migrations.AlterField(
            model_name='messageentity',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_entities', to='andr_update.game'),
        ),
        migrations.AlterField(
            model_name='messageentity',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='andr_update.message'),
        ),
        migrations.AlterField(
            model_name='messageentity',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explanation_entities', to='andr_update.messageentity'),
        ),
    ]
