# Generated by Django 3.1.7 on 2021-04-02 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0011_auto_20210402_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmemberupdated',
            name='from_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='andr_update.andruser'),
        ),
    ]
