# Generated by Django 3.1.7 on 2021-04-02 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0012_auto_20210402_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmemberupdated',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andr_update.update'),
        ),
    ]
