# Generated by Django 3.1.7 on 2021-04-02 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0013_chatmemberupdated_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmemberupdated',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andr_update.chat'),
        ),
    ]
