# Generated by Django 3.1.7 on 2021-04-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0016_auto_20210402_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andruser',
            name='can_join_groups',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_join_groups'),
        ),
        migrations.AlterField(
            model_name='andruser',
            name='can_read_all_group_messages',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_read_all_group_messages'),
        ),
        migrations.AlterField(
            model_name='andruser',
            name='supports_inline_queries',
            field=models.BooleanField(blank=True, null=True, verbose_name='supports_inline_queries'),
        ),
    ]
