# Generated by Django 3.1.7 on 2021-04-02 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0017_auto_20210402_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andruser',
            name='bot_sender',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='via_bot', to='andr_update.message'),
        ),
        migrations.AlterField(
            model_name='andruser',
            name='callback_query',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callback_query_from', to='andr_update.callbackquery'),
        ),
        migrations.AlterField(
            model_name='andruser',
            name='forwarder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_from', to='andr_update.message'),
        ),
        migrations.AlterField(
            model_name='andruser',
            name='inline_query',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_query_from', to='andr_update.inlinequery'),
        ),
        migrations.AlterField(
            model_name='andruser',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to='andr_update.message'),
        ),
        migrations.AlterField(
            model_name='andruser',
            name='user_leaving_member_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_user_member', to='andr_update.message'),
        ),
        migrations.AlterField(
            model_name='andruser',
            name='user_members_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_user_members', to='andr_update.message'),
        ),
    ]
