# Generated by Django 3.1.7 on 2021-04-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0018_auto_20210402_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='can_add_web_page_previews',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_add_web_page_previews'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='can_be_edited',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_be_edited'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='can_change_info',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_change_info'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='can_delete_messages',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_delete_messages'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='can_edit_messages',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_edit_messages'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='can_invite_users',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_invite_users'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='can_manage_chat',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_manage_chat'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='can_manage_voice_chats',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_manage_voice_chats'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='can_pin_messages',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_pin_messages'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='can_post_messages',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_post_messages'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='can_promote_members',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_promote_members'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='can_restrict_members',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_restrict_members'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='can_send_media_messages',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_send_media_messages'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='can_send_messages',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_send_messages'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='can_send_other_messages',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_send_other_messages'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='can_send_polls',
            field=models.BooleanField(blank=True, null=True, verbose_name='can_send_polls'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='is_anonymous',
            field=models.BooleanField(blank=True, null=True, verbose_name='is_anonymous'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='is_member',
            field=models.BooleanField(blank=True, null=True, verbose_name='is_member'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='until_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='until_date'),
        ),
    ]
