# Generated by Django 3.1.7 on 2021-04-02 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0019_auto_20210402_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='new_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_chat_member', to='andr_update.chatmemberupdated'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='old_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_chat_member', to='andr_update.chatmemberupdated'),
        ),
    ]
