# Generated by Django 3.1.7 on 2021-04-02 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0020_auto_20210402_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmemberupdated',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_chat_member', to='andr_update.update'),
        ),
    ]
