# Generated by Django 3.1.7 on 2021-04-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0021_auto_20210402_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maskposition',
            name='sticker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mask_position', to='andr_update.sticker'),
        ),
        migrations.AlterField(
            model_name='photosize',
            name='animation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumb', to='andr_update.animation'),
        ),
        migrations.AlterField(
            model_name='photosize',
            name='audio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumb', to='andr_update.audio'),
        ),
        migrations.AlterField(
            model_name='photosize',
            name='chat_photo_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_chat_photo', to='andr_update.message'),
        ),
        migrations.AlterField(
            model_name='photosize',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumb', to='andr_update.document'),
        ),
        migrations.AlterField(
            model_name='photosize',
            name='file_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='file_size'),
        ),
        migrations.AlterField(
            model_name='photosize',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='andr_update.game'),
        ),
        migrations.AlterField(
            model_name='photosize',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='andr_update.message'),
        ),
        migrations.AlterField(
            model_name='photosize',
            name='sticker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumb', to='andr_update.sticker'),
        ),
        migrations.AlterField(
            model_name='photosize',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumb', to='andr_update.video'),
        ),
        migrations.AlterField(
            model_name='photosize',
            name='video_note',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumb', to='andr_update.videonote'),
        ),
    ]
