# Generated by Django 3.1.7 on 2021-04-03 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0023_auto_20210403_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='file_size'),
        ),
        migrations.AlterField(
            model_name='document',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='andr_update.message'),
        ),
    ]
