# Generated by Django 3.1.7 on 2021-04-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0025_auto_20210403_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andruser',
            name='forwarder_user',
        ),
        migrations.AddField(
            model_name='andruser',
            name='forwarder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_from', to='andr_update.message'),
        ),
        migrations.AlterField(
            model_name='andruser',
            name='bot_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='via_bot', to='andr_update.message'),
        ),
        migrations.AlterField(
            model_name='andruser',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to='andr_update.message'),
        ),
    ]
