# Generated by Django 3.1.7 on 2021-04-03 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0026_auto_20210403_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andruser',
            name='forwarder',
        ),
        migrations.AddField(
            model_name='message',
            name='forward_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_messages', to='andr_update.andruser'),
        ),
    ]
