# Generated by Django 3.1.7 on 2021-04-03 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0027_auto_20210403_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='update',
        ),
        migrations.RemoveField(
            model_name='message',
            name='update_for_this_channel_post',
        ),
        migrations.RemoveField(
            model_name='message',
            name='update_for_this_edited_channel_post',
        ),
        migrations.RemoveField(
            model_name='message',
            name='update_for_this_edited_message',
        ),
        migrations.AddField(
            model_name='update',
            name='channel_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='update_for_this_channel_post', to='andr_update.message'),
        ),
        migrations.AddField(
            model_name='update',
            name='edited_channel_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='update_for_this_edited_channel_post', to='andr_update.message'),
        ),
        migrations.AddField(
            model_name='update',
            name='edited_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='update_for_this_edited_message', to='andr_update.message'),
        ),
        migrations.AddField(
            model_name='update',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='update', to='andr_update.message'),
        ),
    ]
