# Generated by Django 3.1.7 on 2021-04-06 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0029_auto_20210406_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reply_to_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='andr_update.message'),
        ),
    ]
