# Generated by Django 3.1.7 on 2021-04-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0030_auto_20210406_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andruser',
            name='inline_query',
        ),
        migrations.AddField(
            model_name='inlinequery',
            name='inline_query_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_query', to='andr_update.andruser'),
        ),
    ]
