# Generated by Django 3.1.7 on 2021-04-08 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0031_auto_20210408_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choseninlineresult',
            name='update',
        ),
        migrations.RemoveField(
            model_name='inlinequery',
            name='update',
        ),
        migrations.AddField(
            model_name='update',
            name='chosen_inline_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update', to='andr_update.choseninlineresult'),
        ),
        migrations.AddField(
            model_name='update',
            name='inline_query',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update', to='andr_update.inlinequery'),
        ),
        migrations.AlterField(
            model_name='choseninlineresult',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosen_inline_results', to='andr_update.andruser'),
        ),
        migrations.AlterField(
            model_name='inlinequery',
            name='inline_query_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_query', to='andr_update.andruser'),
        ),
    ]
