# Generated by Django 3.1.7 on 2021-04-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0033_auto_20210408_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_user',
        ),
        migrations.AddField(
            model_name='andruser',
            name='message',
            field=models.ManyToManyField(blank=True, null=True, related_name='from_user', to='andr_update.Message'),
        ),
    ]
