# Generated by Django 3.1.7 on 2021-04-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0034_auto_20210408_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andruser',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='from_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='message', to='andr_update.Andruser'),
        ),
    ]
