# Generated by Django 3.1.7 on 2021-04-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0035_auto_20210408_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_user',
        ),
        migrations.AddField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='andr_update.andruser'),
        ),
    ]
