# Generated by Django 3.1.7 on 2021-04-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0036_auto_20210408_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbackquery',
            name='update',
        ),
        migrations.RemoveField(
            model_name='pollanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='precheckoutquery',
            name='update',
        ),
        migrations.RemoveField(
            model_name='shippingquery',
            name='shipping_query_from',
        ),
        migrations.RemoveField(
            model_name='shippingquery',
            name='update',
        ),
        migrations.AddField(
            model_name='pollanswer',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='poll_answers', to='andr_update.andruser'),
        ),
        migrations.AddField(
            model_name='shippingquery',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shipping_queries', to='andr_update.andruser'),
        ),
        migrations.AddField(
            model_name='update',
            name='callback_query',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='update', to='andr_update.callbackquery'),
        ),
        migrations.AddField(
            model_name='update',
            name='poll_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='update', to='andr_update.pollanswer'),
        ),
        migrations.AddField(
            model_name='update',
            name='pre_checkout_query',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='update', to='andr_update.precheckoutquery'),
        ),
        migrations.AddField(
            model_name='update',
            name='shipping_query',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='update', to='andr_update.shippingquery'),
        ),
        migrations.AlterField(
            model_name='precheckoutquery',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_checkout_queries', to='andr_update.andruser'),
        ),
        migrations.AlterField(
            model_name='precheckoutquery',
            name='order_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andr_update.orderinfo'),
        ),
        migrations.AlterField(
            model_name='update',
            name='chosen_inline_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='update', to='andr_update.choseninlineresult'),
        ),
        migrations.AlterField(
            model_name='update',
            name='inline_query',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='update', to='andr_update.inlinequery'),
        ),
    ]
