# Generated by Django 3.1.7 on 2021-04-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0037_auto_20210408_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='_id',
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_id',
            field=models.TextField(blank=True, null=True, verbose_name='poll_id'),
        ),
        migrations.AlterField(
            model_name='messageentity',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explanation_entities', to='andr_update.poll'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='andr_update.message'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=300, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='update',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='andr_update.update'),
        ),
    ]
