# Generated by Django 3.1.7 on 2021-04-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0038_auto_20210408_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='allows_multiple_answers',
            field=models.BooleanField(null=True, verbose_name='allows_multiple_answers'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='close_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='close_date'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='correct_option_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='correct_option_id'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='is_anonymous',
            field=models.BooleanField(null=True, verbose_name='is_anonymous'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='is_closed',
            field=models.BooleanField(null=True, verbose_name='is_closed'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='open_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='open_period'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='total_voter_count',
            field=models.IntegerField(null=True, verbose_name='total_voter_count'),
        ),
    ]
