# Generated by Django 3.1.7 on 2021-04-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0039_auto_20210408_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='andr_update.poll'),
        ),
    ]
