# Generated by Django 3.1.7 on 2021-04-09 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0040_auto_20210409_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andruser',
            name='user_leaving_member_message',
        ),
        migrations.RemoveField(
            model_name='andruser',
            name='user_members_message',
        ),
        migrations.AddField(
            model_name='andruser',
            name='new_to_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_chat_members', to='andr_update.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='left_chat_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='messages_left_from', to='andr_update.andruser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='forward_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='forwarded_messages', to='andr_update.andruser'),
        ),
    ]
