# Generated by Django 3.1.7 on 2021-04-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0041_auto_20210409_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andruser',
            name='bot_sender',
        ),
        migrations.AddField(
            model_name='message',
            name='via_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='messages_via_this_bot', to='andr_update.andruser'),
        ),
    ]
