# Generated by Django 3.1.7 on 2021-04-09 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0042_auto_20210409_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmemberupdated',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andr_update.andruser'),
        ),
    ]
