# Generated by Django 3.1.7 on 2021-04-10 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0044_auto_20210409_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmemberupdated',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='andr_update.chat'),
        ),
        migrations.AlterField(
            model_name='chatmemberupdated',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='andr_update.andruser'),
        ),
        migrations.AlterField(
            model_name='chatmemberupdated',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='my_chat_member', to='andr_update.update'),
        ),
        migrations.AlterField(
            model_name='messageentity',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='text_entities', to='andr_update.game'),
        ),
        migrations.AlterField(
            model_name='messageentity',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='entities', to='andr_update.message'),
        ),
        migrations.AlterField(
            model_name='messageentity',
            name='message_captioned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='caption_entities', to='andr_update.message'),
        ),
        migrations.AlterField(
            model_name='messageentity',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='explanation_entities', to='andr_update.poll'),
        ),
        migrations.AlterField(
            model_name='messageentity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mentions', to='andr_update.andruser'),
        ),
    ]
