# Generated by Django 3.1.7 on 2021-04-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0047_auto_20210412_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='voice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='message', to='andr_update.voice'),
        ),
    ]
