# Generated by Django 3.1.7 on 2021-04-12 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0048_auto_20210412_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='message', to='andr_update.document'),
        ),
    ]
