# Generated by Django 3.1.7 on 2021-04-12 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0050_auto_20210412_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='message',
        ),
        migrations.RemoveField(
            model_name='videonote',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='message', to='andr_update.video'),
        ),
        migrations.AddField(
            model_name='message',
            name='video_note',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='message', to='andr_update.videonote'),
        ),
    ]
