# Generated by Django 3.1.7 on 2021-05-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_update', '0051_auto_20210412_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='status',
            field=models.CharField(choices=[(1, 'Unprocessed'), (2, 'Processed'), (3, 'Error')], default=1, max_length=250),
        ),
    ]
